/* This file is generated by scripts/import-vdot-coaches.mjs. */
export const VDOT_COACHES = [
  {
    "slug": "coach-alli-felsenthal",
    "name": "Alli Felsenthal",
    "city": "Online",
    "location": "Brooklyn, New York, United States",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Alli Felsenthal offers online and in-person running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Alli Felsenthal's public website describes online and in-person coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.runafastermarathon.com/",
    "source": {
      "name": "runafastermarathon.com",
      "url": "https://www.runafastermarathon.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/alli-felsenthal"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-amanda-hoang",
    "name": "Amanda Hoang",
    "city": "Online",
    "location": "Houston, Texas, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Track and cross-country"
    ],
    "blurb": "Amanda Hoang offers online running coaching with a focus on personalized training, strength training and track and cross-country.",
    "bio": [
      "Amanda Hoang's public website describes online coaching focused on personalized training, strength training and track and cross-country."
    ],
    "link": "https://www.mandymovez.com/",
    "source": {
      "name": "mandymovez.com",
      "url": "https://www.mandymovez.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/amanda-hoang"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-amy-windle",
    "name": "Amy Windle",
    "city": "Online",
    "location": "Langley, BC, Canada",
    "format": "online",
    "focus": [
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Injury-aware training"
    ],
    "blurb": "Amy Windle offers online running coaching with a focus on personalized training, strength training and injury-aware training.",
    "bio": [
      "Amy Windle's public website describes online coaching focused on personalized training, strength training and injury-aware training."
    ],
    "link": "https://coachamywindle.my.canva.site/",
    "source": {
      "name": "coachamywindle.my.canva.site",
      "url": "https://coachamywindle.my.canva.site/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/amy-windle"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-andie-cozzarelli",
    "name": "Andie Cozzarelli",
    "city": "Online",
    "location": "Chattanooga, Tennessee, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Andie Cozzarelli offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Andie Cozzarelli's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://run4acozz.com/",
    "source": {
      "name": "run4acozz.com",
      "url": "https://run4acozz.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/andie-cozzarelli"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-andy-mcghee-coaching",
    "name": "Andy McGhee",
    "city": "Online",
    "location": "Southampton, Hampshire, United Kingdom",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware",
      "triathlon"
    ],
    "specialties": [
      "Strength training",
      "Trail and ultrarunning",
      "Track and cross-country",
      "Triathlon",
      "Marathon"
    ],
    "blurb": "Andy McGhee offers online and in-person running coaching with a focus on strength training, trail and ultrarunning and track and cross-country.",
    "bio": [
      "Andy McGhee's public website describes online and in-person coaching focused on strength training, trail and ultrarunning and track and cross-country."
    ],
    "link": "https://andymcgheecoaching.com/",
    "source": {
      "name": "andymcgheecoaching.com",
      "url": "https://andymcgheecoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/andy-mcghee-coaching"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-angela-reckart",
    "name": "Angela Reckart",
    "city": "Online",
    "location": "Cape May Court House, New Jersey, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Track and cross-country",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Angela Reckart offers online running coaching with a focus on strength training, track and cross-country and marathon.",
    "bio": [
      "Angela Reckart's public website describes online coaching focused on strength training, track and cross-country and marathon."
    ],
    "link": "https://www.ngucoaching.com/",
    "source": {
      "name": "ngucoaching.com",
      "url": "https://www.ngucoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/angela-reckart"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-performancephysique",
    "name": "Arj Thiruchelvam",
    "city": "Online",
    "location": "Solihull, Birmingham, United Kingdom",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "performance"
    ],
    "specialties": [
      "Nutrition",
      "Track and cross-country",
      "Beginner runners"
    ],
    "blurb": "Arj Thiruchelvam offers online and in-person running coaching with a focus on nutrition, track and cross-country and beginner runners.",
    "bio": [
      "Arj Thiruchelvam's public website describes online and in-person coaching focused on nutrition, track and cross-country and beginner runners."
    ],
    "link": "https://performancephysique.co.uk/",
    "source": {
      "name": "performancephysique.co.uk",
      "url": "https://performancephysique.co.uk/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/performancephysique"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-backroadsendurance",
    "name": "Backroads Endurance",
    "city": "Online",
    "location": "Noblesville, Indiana, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Beginner runners"
    ],
    "blurb": "Backroads Endurance offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Backroads Endurance's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.backroadsendurance.com/",
    "source": {
      "name": "backroadsendurance.com",
      "url": "https://www.backroadsendurance.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/backroadsendurance"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-tayloredtraining",
    "name": "Becky Anthony",
    "city": "Online",
    "location": "Phoenix, Arizona, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Injury-aware training",
      "Marathon"
    ],
    "blurb": "Becky Anthony offers online running coaching with a focus on personalized training, strength training and injury-aware training.",
    "bio": [
      "Becky Anthony's public website describes online coaching focused on personalized training, strength training and injury-aware training."
    ],
    "link": "https://tayloredtrainingrun.com/",
    "source": {
      "name": "tayloredtrainingrun.com",
      "url": "https://tayloredtrainingrun.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/tayloredtraining"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-becky-croft",
    "name": "Becky Croft",
    "city": "Online",
    "location": "Tulsa, OK, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Becky Croft offers online running coaching with a focus on strength training, nutrition and injury-aware training.",
    "bio": [
      "Becky Croft's public website describes online coaching focused on strength training, nutrition and injury-aware training."
    ],
    "link": "https://hustle-eat-thrive.myshopify.com/",
    "source": {
      "name": "hustle-eat-thrive.myshopify.com",
      "url": "https://hustle-eat-thrive.myshopify.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/becky-croft"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-ben-lauder-dykes",
    "name": "Ben Lauder Dykes",
    "city": "New York",
    "location": "New York, New York, United Kingdom",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Ben Lauder Dykes offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Ben Lauder Dykes's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://bldapproved.com/",
    "source": {
      "name": "bldapproved.com",
      "url": "https://bldapproved.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/ben-lauder-dykes"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-bonnie-wilder",
    "name": "Bonnie Wilder",
    "city": "Online",
    "location": "West Hartford, Connecticut, United States",
    "format": "hybrid",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Bonnie Wilder offers online and in-person running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Bonnie Wilder's public website describes online and in-person coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://runningtheextramiles.com/",
    "source": {
      "name": "runningtheextramiles.com",
      "url": "https://runningtheextramiles.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/bonnie-wilder"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-roadrunnercoaching",
    "name": "Brian Lock",
    "city": "Online",
    "location": "Dunlap, Illinois, USA",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Injury-aware training",
      "Beginner runners",
      "Boston qualifying",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Brian Lock offers online running coaching with a focus on injury-aware training, beginner runners and boston qualifying.",
    "bio": [
      "Brian Lock's public website describes online coaching focused on injury-aware training, beginner runners and boston qualifying."
    ],
    "link": "https://roadrunnercoaching.com/",
    "source": {
      "name": "roadrunnercoaching.com",
      "url": "https://roadrunnercoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/roadrunnercoaching"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-bridget-oldenburg-1",
    "name": "Bridget Oldenburg",
    "city": "Online",
    "location": "Spring, TX, USA",
    "format": "online",
    "focus": [
      "5k-10k",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Track and cross-country",
      "Boston qualifying"
    ],
    "blurb": "Bridget Oldenburg offers online running coaching with a focus on personalized training, track and cross-country and boston qualifying.",
    "bio": [
      "Bridget Oldenburg's public website describes online coaching focused on personalized training, track and cross-country and boston qualifying."
    ],
    "link": "https://runwithurheart.com/",
    "source": {
      "name": "runwithurheart.com",
      "url": "https://runwithurheart.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/bridget-oldenburg-1"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-brooklynn-harvey",
    "name": "Brooklynn Harvey",
    "city": "Online",
    "location": "Pendleton, Indiana, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Trail and ultrarunning"
    ],
    "blurb": "Brooklynn Harvey offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Brooklynn Harvey's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.47runcoaching.com/",
    "source": {
      "name": "47runcoaching.com",
      "url": "https://www.47runcoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/brooklynn-harvey"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-carolinehogardhrunning",
    "name": "Caroline Högardh",
    "city": "Online",
    "location": "Stockholm, Stockholm, Sweden",
    "format": "online",
    "focus": [
      "marathon"
    ],
    "specialties": [
      "Marathon"
    ],
    "blurb": "Caroline Högardh offers online running coaching with a focus on marathon.",
    "bio": [
      "Caroline Högardh's public website describes online coaching focused on marathon."
    ],
    "link": "https://carolinehogardhrunning.webnode.se/",
    "source": {
      "name": "carolinehogardhrunning.webnode.se",
      "url": "https://carolinehogardhrunning.webnode.se/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/carolinehogardhrunning"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-cary-morgan",
    "name": "Cary Morgan",
    "city": "Online",
    "location": "Vestavia, Alabama, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Injury-aware training",
      "Trail and ultrarunning",
      "Track and cross-country",
      "Marathon"
    ],
    "blurb": "Cary Morgan offers online running coaching with a focus on personalized training, injury-aware training and trail and ultrarunning.",
    "bio": [
      "Cary Morgan's public website describes online coaching focused on personalized training, injury-aware training and trail and ultrarunning."
    ],
    "link": "https://www.cadenceruncoaching.com/",
    "source": {
      "name": "cadenceruncoaching.com",
      "url": "https://www.cadenceruncoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/cary-morgan"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-charathoner",
    "name": "Char Griess",
    "city": "Online",
    "location": "Erie, Colorado, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Char Griess offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Char Griess's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.charathoner.com/",
    "source": {
      "name": "charathoner.com",
      "url": "https://www.charathoner.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/charathoner"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-christina-mather",
    "name": "Christina Mather",
    "city": "Online",
    "location": "Fort Worth, Texas, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon"
    ],
    "specialties": [
      "Personalized training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country",
      "Marathon"
    ],
    "blurb": "Christina Mather offers online running coaching with a focus on personalized training, nutrition and injury-aware training.",
    "bio": [
      "Christina Mather's public website describes online coaching focused on personalized training, nutrition and injury-aware training."
    ],
    "link": "https://mathercoachingservices.weebly.com/",
    "source": {
      "name": "mathercoachingservices.weebly.com",
      "url": "https://mathercoachingservices.weebly.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/christina-mather"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-dami-alao",
    "name": "Dami Alao",
    "city": "Online",
    "location": "Alexandria, Virginia, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Injury-aware training",
      "Trail and ultrarunning",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Dami Alao offers online running coaching with a focus on strength training, injury-aware training and trail and ultrarunning.",
    "bio": [
      "Dami Alao's public website describes online coaching focused on strength training, injury-aware training and trail and ultrarunning."
    ],
    "link": "https://www.trainbaseline.net/",
    "source": {
      "name": "trainbaseline.net",
      "url": "https://www.trainbaseline.net/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/dami-alao"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-david-abbott",
    "name": "David Abbott",
    "city": "Online",
    "location": "Sacramento, California, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Masters runners"
    ],
    "blurb": "David Abbott offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "David Abbott's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "http://davidabbott.io/",
    "source": {
      "name": "davidabbott.io",
      "url": "http://davidabbott.io/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/david-abbott"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-eta",
    "name": "David Schwinger - ETA",
    "city": "Online",
    "location": "Rochester, New York, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "5K and 10K"
    ],
    "blurb": "David Schwinger - ETA offers online running coaching with a focus on personalized training, strength training and 5k and 10k.",
    "bio": [
      "David Schwinger - ETA's public website describes online coaching focused on personalized training, strength training and 5k and 10k."
    ],
    "link": "https://endurancetrainingalliance.com/",
    "source": {
      "name": "endurancetrainingalliance.com",
      "url": "https://endurancetrainingalliance.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/eta"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-dimitris-kyriakopoulos",
    "name": "Dimitris Kyriakopoulos",
    "city": "Online",
    "location": "Athens, Attica, Greece",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Marathon",
      "5K and 10K"
    ],
    "blurb": "Dimitris Kyriakopoulos offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Dimitris Kyriakopoulos's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://your-running-university.myshopify.com/",
    "source": {
      "name": "your-running-university.myshopify.com",
      "url": "https://your-running-university.myshopify.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/dimitris-kyriakopoulos"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-dylan-belles",
    "name": "Dylan Belles",
    "city": "Online",
    "location": "Eureka, Missouri, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Masters runners"
    ],
    "blurb": "Dylan Belles offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Dylan Belles's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.dylanbelles.com/",
    "source": {
      "name": "dylanbelles.com",
      "url": "https://www.dylanbelles.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/dylan-belles"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-endurance4you",
    "name": "Elizabeth Miller",
    "city": "Online",
    "location": "San Antonio, Texas, United States",
    "format": "online",
    "focus": [
      "performance"
    ],
    "specialties": [
      "Personalized training"
    ],
    "blurb": "Elizabeth Miller offers online running coaching with a focus on personalized training.",
    "bio": [
      "Elizabeth Miller's public website describes online coaching focused on personalized training."
    ],
    "link": "https://endurance4you.com/run-coaching/",
    "source": {
      "name": "endurance4you.com",
      "url": "https://endurance4you.com/run-coaching/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/endurance4you"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-evan-schwartz",
    "name": "Evan Schwartz",
    "city": "Online",
    "location": "Boulder, Colorado, United States",
    "format": "online",
    "focus": [
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Marathon"
    ],
    "blurb": "Evan Schwartz offers online running coaching with a focus on personalized training and marathon.",
    "bio": [
      "Evan Schwartz's public website describes online coaching focused on personalized training and marathon."
    ],
    "link": "https://www.evanschwartzcoaching.com/",
    "source": {
      "name": "evanschwartzcoaching.com",
      "url": "https://www.evanschwartzcoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/evan-schwartz"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-eat-fitness",
    "name": "Evan Titus",
    "city": "Online",
    "location": "Norwalk, Connecticut, United States",
    "format": "online",
    "focus": [
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Nutrition"
    ],
    "blurb": "Evan Titus offers online running coaching with a focus on strength training and nutrition.",
    "bio": [
      "Evan Titus's public website describes online coaching focused on strength training and nutrition."
    ],
    "link": "https://www.evantitusfitness.com/",
    "source": {
      "name": "evantitusfitness.com",
      "url": "https://www.evantitusfitness.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/eat-fitness"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-fleetfeetnashville",
    "name": "Fleet Feet Nashville",
    "city": "Online",
    "location": "Nashville, TN, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Injury-aware training",
      "Track and cross-country",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Fleet Feet Nashville offers online running coaching with a focus on personalized training, injury-aware training and track and cross-country.",
    "bio": [
      "Fleet Feet Nashville's public website describes online coaching focused on personalized training, injury-aware training and track and cross-country."
    ],
    "link": "https://www.fleetfeet.com/s/nashville/",
    "source": {
      "name": "fleetfeet.com",
      "url": "https://www.fleetfeet.com/s/nashville/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/fleetfeetnashville"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-gaby-go",
    "name": "Gaby Go",
    "city": "Online",
    "location": "Bethesda, Maryland, United States",
    "format": "hybrid",
    "focus": [
      "first-timers",
      "5k-10k",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Gaby Go offers online and in-person running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Gaby Go's public website describes online and in-person coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://gorunstronger.com/",
    "source": {
      "name": "gorunstronger.com",
      "url": "https://gorunstronger.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/gaby-go"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-hannah-shakeshaft",
    "name": "Hannah Shakeshaft",
    "city": "Online",
    "location": "Philadelphia, Pennsylvania, United States",
    "format": "online",
    "focus": [
      "performance"
    ],
    "specialties": [
      "Individual running coaching"
    ],
    "blurb": "Hannah Shakeshaft offers online running coaching with a focus on individual running coaching.",
    "bio": [
      "Hannah Shakeshaft's public website describes online coaching focused on individual running coaching."
    ],
    "link": "https://www.overlaprunning.com/",
    "source": {
      "name": "overlaprunning.com",
      "url": "https://www.overlaprunning.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/hannah-shakeshaft"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-heather-caplan-rdn",
    "name": "Heather Caplan RDN",
    "city": "Online",
    "location": "No, Michigan, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "performance"
    ],
    "specialties": [
      "Nutrition",
      "Trail and ultrarunning",
      "Track and cross-country",
      "5K and 10K"
    ],
    "blurb": "Heather Caplan RDN offers online running coaching with a focus on nutrition, trail and ultrarunning and track and cross-country.",
    "bio": [
      "Heather Caplan RDN's public website describes online coaching focused on nutrition, trail and ultrarunning and track and cross-country."
    ],
    "link": "https://heathercaplan.com/",
    "source": {
      "name": "heathercaplan.com",
      "url": "https://heathercaplan.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/heather-caplan-rdn"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-ian-paramore",
    "name": "Ian Paramore",
    "city": "Online",
    "location": "Loughborough, Leicestershire, United Kingdom",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon"
    ],
    "specialties": [
      "Injury-aware training",
      "Track and cross-country",
      "Marathon",
      "5K and 10K"
    ],
    "blurb": "Ian Paramore offers online running coaching with a focus on injury-aware training, track and cross-country and marathon.",
    "bio": [
      "Ian Paramore's public website describes online coaching focused on injury-aware training, track and cross-country and marathon."
    ],
    "link": "https://runnerbeancoaching.wordpress.com/",
    "source": {
      "name": "runnerbeancoaching.wordpress.com",
      "url": "https://runnerbeancoaching.wordpress.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/ian-paramore"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-risereigntraining",
    "name": "Jillian Reyna",
    "city": "Online",
    "location": "Akron, Ohio, United States",
    "format": "online",
    "focus": [
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Marathon"
    ],
    "blurb": "Jillian Reyna offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Jillian Reyna's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.risereigntraining.com/",
    "source": {
      "name": "risereigntraining.com",
      "url": "https://www.risereigntraining.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/risereigntraining"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-coach-joe-shayne",
    "name": "Joe Shayne",
    "city": "Online",
    "location": "Brooklyn, New York, United States",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Injury-aware training",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Joe Shayne offers online and in-person running coaching with a focus on personalized training, strength training and injury-aware training.",
    "bio": [
      "Joe Shayne's public website describes online and in-person coaching focused on personalized training, strength training and injury-aware training."
    ],
    "link": "https://werunkings.com/",
    "source": {
      "name": "werunkings.com",
      "url": "https://werunkings.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/coach-joe-shayne"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-jonathan-lyau",
    "name": "Jonathan Lyau",
    "city": "Online",
    "location": "Honolulu, Hawaii, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Nutrition",
      "Track and cross-country",
      "Beginner runners",
      "Marathon"
    ],
    "blurb": "Jonathan Lyau offers online running coaching with a focus on personalized training, nutrition and track and cross-country.",
    "bio": [
      "Jonathan Lyau's public website describes online coaching focused on personalized training, nutrition and track and cross-country."
    ],
    "link": "https://personalbesttraininghi.com/",
    "source": {
      "name": "personalbesttraininghi.com",
      "url": "https://personalbesttraininghi.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/jonathan-lyau"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-joseph-winwood",
    "name": "Joseph Winwood",
    "city": "Online",
    "location": "Dallas, Texas, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "half",
      "marathon"
    ],
    "specialties": [
      "Trail and ultrarunning",
      "Beginner runners",
      "Marathon",
      "Half marathon",
      "5K and 10K"
    ],
    "blurb": "Joseph Winwood offers online running coaching with a focus on trail and ultrarunning, beginner runners and marathon.",
    "bio": [
      "Joseph Winwood's public website describes online coaching focused on trail and ultrarunning, beginner runners and marathon."
    ],
    "link": "https://www.southernmostrunningco.com/",
    "source": {
      "name": "southernmostrunningco.com",
      "url": "https://www.southernmostrunningco.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/joseph-winwood"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-karen-dunn",
    "name": "Karen Dunn",
    "city": "Online",
    "location": "Collegeville, Pennsylvania, United States",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Karen Dunn offers online and in-person running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Karen Dunn's public website describes online and in-person coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.strengthenyourstride.coach/",
    "source": {
      "name": "strengthenyourstride.coach",
      "url": "https://www.strengthenyourstride.coach/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/karen-dunn"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-coachkarli",
    "name": "Karli Saur",
    "city": "Online",
    "location": "Bernardsville, New Jersey, United States",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Nutrition",
      "Track and cross-country"
    ],
    "blurb": "Karli Saur offers online and in-person running coaching with a focus on strength training, nutrition and track and cross-country.",
    "bio": [
      "Karli Saur's public website describes online and in-person coaching focused on strength training, nutrition and track and cross-country."
    ],
    "link": "https://www.irondiamondfitness.com/",
    "source": {
      "name": "irondiamondfitness.com",
      "url": "https://www.irondiamondfitness.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/coachkarli"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-runwildcoaching",
    "name": "Kasey Halbleib",
    "city": "Online",
    "location": "Philadelphia, Pennsylvania, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Track and cross-country",
      "Beginner runners",
      "Marathon"
    ],
    "blurb": "Kasey Halbleib offers online running coaching with a focus on personalized training, track and cross-country and beginner runners.",
    "bio": [
      "Kasey Halbleib's public website describes online coaching focused on personalized training, track and cross-country and beginner runners."
    ],
    "link": "https://runwildcoaching.fit/",
    "source": {
      "name": "runwildcoaching.fit",
      "url": "https://runwildcoaching.fit/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/runwildcoaching"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-kim-elia",
    "name": "Kim Elia",
    "city": "Online",
    "location": "Hudson, MA, USA",
    "format": "online",
    "focus": [
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Injury-aware training",
      "Marathon"
    ],
    "blurb": "Kim Elia offers online running coaching with a focus on personalized training, strength training and injury-aware training.",
    "bio": [
      "Kim Elia's public website describes online coaching focused on personalized training, strength training and injury-aware training."
    ],
    "link": "https://www.orthonept.com/",
    "source": {
      "name": "orthonept.com",
      "url": "https://www.orthonept.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/kim-elia"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-kristyn-r-smith",
    "name": "Kristyn R Smith",
    "city": "New York",
    "location": "New York, New York, United States",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Kristyn R Smith offers online and in-person running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Kristyn R Smith's public website describes online and in-person coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://coachkrisrs.com/",
    "source": {
      "name": "coachkrisrs.com",
      "url": "https://coachkrisrs.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/kristyn-r-smith"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-scissortailrunning",
    "name": "Kyle McKinley",
    "city": "Online",
    "location": "Edmond, Oklahoma, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Trail and ultrarunning",
      "Track and cross-country"
    ],
    "blurb": "Kyle McKinley offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Kyle McKinley's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.scissortailrunning.com/",
    "source": {
      "name": "scissortailrunning.com",
      "url": "https://www.scissortailrunning.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/scissortailrunning"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-coachlaurafilla",
    "name": "Laura Filla",
    "city": "Online",
    "location": "St. Louis, Missouri, United States",
    "format": "hybrid",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Laura Filla offers online and in-person running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Laura Filla's public website describes online and in-person coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://fillaendurance.com/",
    "source": {
      "name": "fillaendurance.com",
      "url": "https://fillaendurance.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/coachlaurafilla"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-leahrosenfeld",
    "name": "Leah Rosenfeld",
    "city": "Los Angeles",
    "location": "Los Angeles, California, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Leah Rosenfeld offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Leah Rosenfeld's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.leahrosenfeld.com/",
    "source": {
      "name": "leahrosenfeld.com",
      "url": "https://www.leahrosenfeld.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/leahrosenfeld"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-runstark",
    "name": "Liam Struwe",
    "city": "Online",
    "location": "Hertford, Hertfordshire, United Kingdom",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Track and cross-country",
      "Marathon"
    ],
    "blurb": "Liam Struwe offers online running coaching with a focus on strength training, track and cross-country and marathon.",
    "bio": [
      "Liam Struwe's public website describes online coaching focused on strength training, track and cross-country and marathon."
    ],
    "link": "https://runstark.co.uk/home-1",
    "source": {
      "name": "runstark.co.uk",
      "url": "https://runstark.co.uk/home-1"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/runstark"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-lindseyaltermatt",
    "name": "Lindsey Altermatt",
    "city": "Online",
    "location": "St. Francis, Minnesota, United States",
    "format": "online",
    "focus": [
      "5k-10k"
    ],
    "specialties": [
      "Trail and ultrarunning"
    ],
    "blurb": "Lindsey Altermatt offers online running coaching with a focus on trail and ultrarunning.",
    "bio": [
      "Lindsey Altermatt's public website describes online coaching focused on trail and ultrarunning."
    ],
    "link": "https://mntrailruncollective.com/",
    "source": {
      "name": "mntrailruncollective.com",
      "url": "https://mntrailruncollective.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/lindseyaltermatt"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-louis-serafini",
    "name": "Louis Serafini",
    "city": "Online",
    "location": "North Cambridge, Massachusetts, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon"
    ],
    "specialties": [
      "Personalized training",
      "Marathon",
      "Half marathon",
      "5K and 10K"
    ],
    "blurb": "Louis Serafini offers online running coaching with a focus on personalized training, marathon and half marathon.",
    "bio": [
      "Louis Serafini's public website describes online coaching focused on personalized training, marathon and half marathon."
    ],
    "link": "https://serafinicoaching.run/",
    "source": {
      "name": "serafinicoaching.run",
      "url": "https://serafinicoaching.run/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/louis-serafini"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-maddie",
    "name": "Maddie Barrett",
    "city": "Online",
    "location": "Minneapolis, Minnesota, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon"
    ],
    "specialties": [
      "Track and cross-country",
      "Marathon",
      "5K and 10K"
    ],
    "blurb": "Maddie Barrett offers online running coaching with a focus on track and cross-country, marathon and 5k and 10k.",
    "bio": [
      "Maddie Barrett's public website describes online coaching focused on track and cross-country, marathon and 5k and 10k."
    ],
    "link": "https://www.joyfulrunningcoaching.com/",
    "source": {
      "name": "joyfulrunningcoaching.com",
      "url": "https://www.joyfulrunningcoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/maddie"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-malindi-elmore",
    "name": "Malindi Elmore",
    "city": "Online",
    "location": "Kelowna, BC, Canada",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware",
      "triathlon"
    ],
    "specialties": [
      "Strength training",
      "Track and cross-country",
      "Triathlon",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Malindi Elmore offers online running coaching with a focus on strength training, track and cross-country and triathlon.",
    "bio": [
      "Malindi Elmore's public website describes online coaching focused on strength training, track and cross-country and triathlon."
    ],
    "link": "https://malindielmore.com/",
    "source": {
      "name": "malindielmore.com",
      "url": "https://malindielmore.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/malindi-elmore"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-mark-day",
    "name": "Mark Day",
    "city": "Online",
    "location": "Cheltenham, Gloucestershire, United Kingdom",
    "format": "online",
    "focus": [
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Trail and ultrarunning",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Mark Day offers online running coaching with a focus on strength training, trail and ultrarunning and marathon.",
    "bio": [
      "Mark Day's public website describes online coaching focused on strength training, trail and ultrarunning and marathon."
    ],
    "link": "https://racewithoutfear.com/",
    "source": {
      "name": "racewithoutfear.com",
      "url": "https://racewithoutfear.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/mark-day"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-amrunningvb",
    "name": "Matt Hotaling",
    "city": "Online",
    "location": "Virginia Beach, Virginia, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware",
      "triathlon"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Track and cross-country",
      "Boston qualifying",
      "Triathlon"
    ],
    "blurb": "Matt Hotaling offers online running coaching with a focus on personalized training, strength training and track and cross-country.",
    "bio": [
      "Matt Hotaling's public website describes online coaching focused on personalized training, strength training and track and cross-country."
    ],
    "link": "https://sites.google.com/view/amrunningvb",
    "source": {
      "name": "sites.google.com",
      "url": "https://sites.google.com/view/amrunningvb"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/amrunningvb"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-lopiccolo",
    "name": "Matt LoPiccolo",
    "city": "Online",
    "location": "Apex, North Carolina, United States",
    "format": "hybrid",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Injury-aware training",
      "Track and cross-country",
      "Marathon",
      "5K and 10K"
    ],
    "blurb": "Matt LoPiccolo offers online and in-person running coaching with a focus on personalized training, injury-aware training and track and cross-country.",
    "bio": [
      "Matt LoPiccolo's public website describes online and in-person coaching focused on personalized training, injury-aware training and track and cross-country."
    ],
    "link": "https://lopiccoloendurance.com/",
    "source": {
      "name": "lopiccoloendurance.com",
      "url": "https://lopiccoloendurance.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/lopiccolo"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-megan-cooke",
    "name": "Megan Cooke",
    "city": "Online",
    "location": "Hillsborough, North Carolina, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Track and cross-country",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Megan Cooke offers online running coaching with a focus on strength training, track and cross-country and marathon.",
    "bio": [
      "Megan Cooke's public website describes online coaching focused on strength training, track and cross-country and marathon."
    ],
    "link": "https://www.ngucoaching.com/",
    "source": {
      "name": "ngucoaching.com",
      "url": "https://www.ngucoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/megan-cooke"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-michelle-baxter",
    "name": "Michelle Baxter",
    "city": "Online",
    "location": ", Minnesota, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Nutrition",
      "Marathon"
    ],
    "blurb": "Michelle Baxter offers online running coaching with a focus on nutrition and marathon.",
    "bio": [
      "Michelle Baxter's public website describes online coaching focused on nutrition and marathon."
    ],
    "link": "https://www.therunnersplate.com/",
    "source": {
      "name": "therunnersplate.com",
      "url": "https://www.therunnersplate.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/michelle-baxter"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-mikkelgislejohnsen",
    "name": "Mikkel Gisle Johnsen",
    "city": "Online",
    "location": "Oslo, Norway, Norway",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Marathon"
    ],
    "blurb": "Mikkel Gisle Johnsen offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Mikkel Gisle Johnsen's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.mgjcoaching.no/international",
    "source": {
      "name": "mgjcoaching.no",
      "url": "https://www.mgjcoaching.no/international"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/mikkelgislejohnsen"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-rundreamachieve",
    "name": "Nathan Pennington",
    "city": "Online",
    "location": "Grand Haven, Michigan, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Track and cross-country",
      "Beginner runners"
    ],
    "blurb": "Nathan Pennington offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Nathan Pennington's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://rundreamachieve.com/",
    "source": {
      "name": "rundreamachieve.com",
      "url": "https://rundreamachieve.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/rundreamachieve"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-magnumopuscoaching",
    "name": "Nelle Gray",
    "city": "Online",
    "location": "Bridgewater, Virginia, United States",
    "format": "hybrid",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Trail and ultrarunning"
    ],
    "blurb": "Nelle Gray offers online and in-person running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Nelle Gray's public website describes online and in-person coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.magnumopuscoaching.com/",
    "source": {
      "name": "magnumopuscoaching.com",
      "url": "https://www.magnumopuscoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/magnumopuscoaching"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-coachnih",
    "name": "Nialah Ferrer",
    "city": "Online",
    "location": "Washington D.C and NYC, New York, United States",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Injury-aware training",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Nialah Ferrer offers online and in-person running coaching with a focus on personalized training, strength training and injury-aware training.",
    "bio": [
      "Nialah Ferrer's public website describes online and in-person coaching focused on personalized training, strength training and injury-aware training."
    ],
    "link": "https://werunkings.com/",
    "source": {
      "name": "werunkings.com",
      "url": "https://werunkings.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/coachnih"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-nicholas-hilton",
    "name": "Nicholas Hilton",
    "city": "Online",
    "location": "Flagstaff, AZ, United States",
    "format": "online",
    "focus": [
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Marathon"
    ],
    "blurb": "Nicholas Hilton offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Nicholas Hilton's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.hiltonperformancerunning.com/",
    "source": {
      "name": "hiltonperformancerunning.com",
      "url": "https://www.hiltonperformancerunning.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/nicholas-hilton"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-noa-besner",
    "name": "Noa Besner",
    "city": "New York",
    "location": "New York, NY, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "half",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Nutrition",
      "Beginner runners",
      "Boston qualifying",
      "Triathlon"
    ],
    "blurb": "Noa Besner offers online running coaching with a focus on personalized training, nutrition and beginner runners.",
    "bio": [
      "Noa Besner's public website describes online coaching focused on personalized training, nutrition and beginner runners."
    ],
    "link": "https://runcoachnoa.com/",
    "source": {
      "name": "runcoachnoa.com",
      "url": "https://runcoachnoa.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/noa-besner"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-pamela-hunt",
    "name": "Pamela Hunt",
    "city": "New York",
    "location": "New York, New York, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Pamela Hunt offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Pamela Hunt's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.orithyia.nyc/coaching",
    "source": {
      "name": "orithyia.nyc",
      "url": "https://www.orithyia.nyc/coaching"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/pamela-hunt"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-petesimon",
    "name": "Pete Simon",
    "city": "Online",
    "location": "Plymouth, Devon, United Kingdom",
    "format": "hybrid",
    "focus": [
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country",
      "Beginner runners"
    ],
    "blurb": "Pete Simon offers online and in-person running coaching with a focus on strength training, nutrition and injury-aware training.",
    "bio": [
      "Pete Simon's public website describes online and in-person coaching focused on strength training, nutrition and injury-aware training."
    ],
    "link": "https://petesimon.com/",
    "source": {
      "name": "petesimon.com",
      "url": "https://petesimon.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/petesimon"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-paulwhittaker",
    "name": "PW Performance Coaching",
    "city": "Online",
    "location": "Southend-on-Sea, Essex, United Kingdom",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Marathon",
      "5K and 10K"
    ],
    "blurb": "PW Performance Coaching offers online running coaching with a focus on marathon and 5k and 10k.",
    "bio": [
      "PW Performance Coaching's public website describes online coaching focused on marathon and 5k and 10k."
    ],
    "link": "https://pwperformancecoaching.com/",
    "source": {
      "name": "pwperformancecoaching.com",
      "url": "https://pwperformancecoaching.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/paulwhittaker"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-rachel-turner",
    "name": "Rachel Turner",
    "city": "Online",
    "location": "Cambridge, Cambridgeshire, United Kingdom",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Nutrition",
      "Injury-aware training",
      "Trail and ultrarunning",
      "Marathon",
      "5K and 10K"
    ],
    "blurb": "Rachel Turner offers online running coaching with a focus on nutrition, injury-aware training and trail and ultrarunning.",
    "bio": [
      "Rachel Turner's public website describes online coaching focused on nutrition, injury-aware training and trail and ultrarunning."
    ],
    "link": "https://runnersnutritioncoach.com/",
    "source": {
      "name": "runnersnutritioncoach.com",
      "url": "https://runnersnutritioncoach.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/rachel-turner"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-richard-airey",
    "name": "Richard Airey",
    "city": "Online",
    "location": "Seneca, South Carolina, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Trail and ultrarunning",
      "Track and cross-country"
    ],
    "blurb": "Richard Airey offers online running coaching with a focus on strength training, nutrition and injury-aware training.",
    "bio": [
      "Richard Airey's public website describes online coaching focused on strength training, nutrition and injury-aware training."
    ],
    "link": "https://www.blacksheependurance.com/",
    "source": {
      "name": "blacksheependurance.com",
      "url": "https://www.blacksheependurance.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/richard-airey"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-riley-coulter",
    "name": "Riley Coulter",
    "city": "Online",
    "location": "Platteville, Wi, United States",
    "format": "online",
    "focus": [
      "performance"
    ],
    "specialties": [
      "Individual running coaching"
    ],
    "blurb": "Riley Coulter offers online running coaching with a focus on individual running coaching.",
    "bio": [
      "Riley Coulter's public website describes online coaching focused on individual running coaching."
    ],
    "link": "https://www.driftlessdistanceproject.com/",
    "source": {
      "name": "driftlessdistanceproject.com",
      "url": "https://www.driftlessdistanceproject.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/riley-coulter"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-roabel",
    "name": "Roabel Medhanie",
    "city": "Online",
    "location": "Oakland, CA, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Injury-aware training",
      "Triathlon",
      "Marathon",
      "Half marathon",
      "5K and 10K"
    ],
    "blurb": "Roabel Medhanie offers online running coaching with a focus on injury-aware training, triathlon and marathon.",
    "bio": [
      "Roabel Medhanie's public website describes online coaching focused on injury-aware training, triathlon and marathon."
    ],
    "link": "https://www.runwithroabel.com/",
    "source": {
      "name": "runwithroabel.com",
      "url": "https://www.runwithroabel.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/roabel"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-sarah-kozul",
    "name": "Sarah Kozul",
    "city": "Online",
    "location": "Lakeland, Florida, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "half",
      "marathon"
    ],
    "specialties": [
      "Personalized training",
      "Injury-aware training",
      "Marathon",
      "Half marathon",
      "5K and 10K"
    ],
    "blurb": "Sarah Kozul offers online running coaching with a focus on personalized training, injury-aware training and marathon.",
    "bio": [
      "Sarah Kozul's public website describes online coaching focused on personalized training, injury-aware training and marathon."
    ],
    "link": "https://runnerssense.com/",
    "source": {
      "name": "runnerssense.com",
      "url": "https://runnerssense.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/sarah-kozul"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-scott-brown",
    "name": "Scott Andrew Brown",
    "city": "Online",
    "location": "Sakai, Osaka, Japan",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "half",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Track and cross-country",
      "Beginner runners",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Scott Andrew Brown offers online and in-person running coaching with a focus on personalized training, track and cross-country and beginner runners.",
    "bio": [
      "Scott Andrew Brown's public website describes online and in-person coaching focused on personalized training, track and cross-country and beginner runners."
    ],
    "link": "https://samurairunningjapan.com/",
    "source": {
      "name": "samurairunningjapan.com",
      "url": "https://samurairunningjapan.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/scott-brown"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-shainacales",
    "name": "Shaina Cales",
    "city": "Online",
    "location": "Boise, Idaho, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance"
    ],
    "specialties": [
      "Personalized training",
      "Nutrition",
      "Marathon",
      "Half marathon",
      "5K and 10K"
    ],
    "blurb": "Shaina Cales offers online running coaching with a focus on personalized training, nutrition and marathon.",
    "bio": [
      "Shaina Cales's public website describes online coaching focused on personalized training, nutrition and marathon."
    ],
    "link": "https://www.sparkrunning.co/",
    "source": {
      "name": "sparkrunning.co",
      "url": "https://www.sparkrunning.co/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/shainacales"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-stuart-lamp",
    "name": "Stuart Lamp",
    "city": "Online",
    "location": "Decatur, Alabama, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "performance"
    ],
    "specialties": [
      "Individual running coaching"
    ],
    "blurb": "Stuart Lamp offers online running coaching with a focus on individual running coaching.",
    "bio": [
      "Stuart Lamp's public website describes online coaching focused on individual running coaching."
    ],
    "link": "https://www.allied-endurance.com/",
    "source": {
      "name": "allied-endurance.com",
      "url": "https://www.allied-endurance.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/stuart-lamp"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-tw-training",
    "name": "Tammy Whyte",
    "city": "Chicago",
    "location": "Chicago, Illinois, United States",
    "format": "online",
    "focus": [
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Marathon"
    ],
    "blurb": "Tammy Whyte offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Tammy Whyte's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.tw-training.com/",
    "source": {
      "name": "tw-training.com",
      "url": "https://www.tw-training.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/tw-training"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-tiffany-england",
    "name": "Tiffany England",
    "city": "Online",
    "location": "Brighton & Hove, East Sussex, United Kingdom",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon"
    ],
    "specialties": [
      "Trail and ultrarunning",
      "Track and cross-country",
      "Beginner runners",
      "Boston qualifying",
      "Marathon"
    ],
    "blurb": "Tiffany England offers online running coaching with a focus on trail and ultrarunning, track and cross-country and beginner runners.",
    "bio": [
      "Tiffany England's public website describes online coaching focused on trail and ultrarunning, track and cross-country and beginner runners."
    ],
    "link": "https://www.englandrunning.com/",
    "source": {
      "name": "englandrunning.com",
      "url": "https://www.englandrunning.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/tiffany-england"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-resilience-run-co",
    "name": "Todd Nickel",
    "city": "Online",
    "location": "Vancouver, BC, Canada",
    "format": "online",
    "focus": [
      "performance"
    ],
    "specialties": [
      "Masters runners"
    ],
    "blurb": "Todd Nickel offers online running coaching with a focus on masters runners.",
    "bio": [
      "Todd Nickel's public website describes online coaching focused on masters runners."
    ],
    "link": "https://resiliencerunco.ca/",
    "source": {
      "name": "resiliencerunco.ca",
      "url": "https://resiliencerunco.ca/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/resilience-run-co"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-fast-pack-running",
    "name": "Tom Palamar and Jenny Crawshaw",
    "city": "Online",
    "location": "New Port Richey, Florida, United States",
    "format": "online",
    "focus": [
      "first-timers",
      "5k-10k",
      "half",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Track and cross-country",
      "Marathon",
      "Half marathon"
    ],
    "blurb": "Tom Palamar and Jenny Crawshaw offers online running coaching with a focus on personalized training, strength training and track and cross-country.",
    "bio": [
      "Tom Palamar and Jenny Crawshaw's public website describes online coaching focused on personalized training, strength training and track and cross-country."
    ],
    "link": "https://fastpackrunning.com/",
    "source": {
      "name": "fastpackrunning.com",
      "url": "https://fastpackrunning.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/fast-pack-running"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-toni-kengor",
    "name": "Toni Kengor",
    "city": "Online",
    "location": "Pittsburgh, PA, United States",
    "format": "online",
    "focus": [
      "performance"
    ],
    "specialties": [
      "Injury-aware training"
    ],
    "blurb": "Toni Kengor offers online running coaching with a focus on injury-aware training.",
    "bio": [
      "Toni Kengor's public website describes online coaching focused on injury-aware training."
    ],
    "link": "https://www.relentlessrunners.com/",
    "source": {
      "name": "relentlessrunners.com",
      "url": "https://www.relentlessrunners.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/toni-kengor"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-trish-dobrowski",
    "name": "Trish Dobrowski",
    "city": "Online",
    "location": "Jersey City, New Jersey, United States",
    "format": "hybrid",
    "focus": [
      "5k-10k",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Track and cross-country"
    ],
    "blurb": "Trish Dobrowski offers online and in-person running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Trish Dobrowski's public website describes online and in-person coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://longrunpt.com/",
    "source": {
      "name": "longrunpt.com",
      "url": "https://longrunpt.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/trish-dobrowski"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-will-baldwin",
    "name": "Will Baldwin",
    "city": "Online",
    "location": "Denver, Colorado, United States",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon",
      "performance",
      "injury-aware"
    ],
    "specialties": [
      "Personalized training",
      "Strength training",
      "Nutrition",
      "Injury-aware training",
      "Trail and ultrarunning"
    ],
    "blurb": "Will Baldwin offers online running coaching with a focus on personalized training, strength training and nutrition.",
    "bio": [
      "Will Baldwin's public website describes online coaching focused on personalized training, strength training and nutrition."
    ],
    "link": "https://www.runbaldwin.com/",
    "source": {
      "name": "runbaldwin.com",
      "url": "https://www.runbaldwin.com/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/will-baldwin"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  },
  {
    "slug": "coach-zwonlinecoach",
    "name": "Zacharias Wedel",
    "city": "Online",
    "location": "Fürth, Bayern, Germany",
    "format": "online",
    "focus": [
      "5k-10k",
      "marathon"
    ],
    "specialties": [
      "Injury-aware training",
      "Marathon",
      "5K and 10K"
    ],
    "blurb": "Zacharias Wedel offers online running coaching with a focus on injury-aware training, marathon and 5k and 10k.",
    "bio": [
      "Zacharias Wedel's public website describes online coaching focused on injury-aware training, marathon and 5k and 10k."
    ],
    "link": "https://www.zacharias-wedel.de/",
    "source": {
      "name": "zacharias-wedel.de",
      "url": "https://www.zacharias-wedel.de/"
    },
    "discoveredFrom": {
      "name": "V.O2 coach marketplace",
      "url": "https://vdoto2.com/running-coach/zwonlinecoach"
    },
    "sourceCheckedAt": "2026-10-03",
    "verified": false
  }
] satisfies import("./coaches").Coach[];
